### ISSUE TITLE
Csv dont created

### ISSUE THREAD

**Issue by ManChrys** [ori-drs/allan_variance_ros#39]
Hello after i running this command `geo@geo:rosrun allan_variance_ros allan_variance /home/geo/allan_ws/cooked.bag /home/geo/allan_ws/src/allan_variance_ros/config/xsens.yaml

i have this 

[ INFO] [1693522390.065245857]: Computed 23 bins for sampling period 999.8 out of 4728000 measurements.
[ INFO] [1693522390.065276365]: Computed 23 bins for sampling period 999.9 out of 4728000 measurements.
[ INFO] [1693522390.124736774]: Total computation time: 727.674321 s
[ INFO] [1693522390.124794165]: Data written to allan_variance.csv

but there is no csv or other file created.

[allan_variance.txt](https://github.com/ori-drs/allan_variance_ros/files/12491545/allan_variance.txt)
[AllanVarianceComputor.txt](https://github.com/ori-drs/allan_variance_ros/files/12491546/AllanVarianceComputor.txt)

Is there something wrong?
Thanks in advance

**EDIT**

Running original.bag using `rostopic echo /imu/data` i had the following

```
`header: 
  seq: 14269
  stamp: 
    secs: 1693464526
    nsecs: 514156465
  frame_id: "imu_link"
orientation: 
  x: -0.00373723677363
  y: 0.00251957299416
  z: -0.01746058324
  w: 0.999837393203
orientation_covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
angular_velocity: 
  x: 0.00422149919905
  y: 0.0120803716127
  z: 3.27825546265e-05
angular_velocity_covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
linear_acceleration: 
  x: -0.0884681791067
  y: -0.0697058513761
  z: 9.7687997818
linear_acceleration_covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
```
`

doing the same thing for the cooked bag i  have data showing but after a time.Cooked rosbag info.

```
`geo@geo-X570-GAMING-X:~/allan_ws$ rosbag info cooked.bag 
path:         cooked.bag
version:      2.0
duration:     4hr 1:50s (14510s)
start:        Aug 31 2023 09:48:10.83 (1693464490.83)
end:          Aug 31 2023 13:50:01.66 (1693479001.66)
size:         1.1 GB
messages:     34926585
compression:  bz2 [6423/6423 chunks; 14.20%]
uncompressed:   4.7 GB @ 340.0 KB/s
compressed:   684.3 MB @  48.3 KB/s (14.20%)
types:        geometry_msgs/QuaternionStamped [e57f1e547e0e1fd13504588ffc8334e2]
              geometry_msgs/Vector3Stamped    [7b324c7325e683bf02a9b14b01090ec7]
              rosgraph_msgs/Log               [acffd30cd6b6de30f120938c17c593fb]
              sensor_msgs/Imu                 [6a62c6daae103f4ff57a132d6f95cec2]
              sensor_msgs/NavSatFix           [2d3a8cd499b9b4a0249fb98fd05cfa48]
              sensor_msgs/TimeReference       [fded64a0265108ba86c3d38fb11c0c16]
              tf2_msgs/TFMessage              [94810edda583a504dfda3829e70d7eec]
topics:       /filter/quaternion      5792134 msgs    : geometry_msgs/QuaternionStamped
              /gnss                     57920 msgs    : sensor_msgs/NavSatFix          
              /imu/acceleration       5792134 msgs    : geometry_msgs/Vector3Stamped   
              /imu/angular_velocity   5792136 msgs    : geometry_msgs/Vector3Stamped   
              /imu/data               5792135 msgs    : sensor_msgs/Imu                
              /imu/time_ref           5907974 msgs    : sensor_msgs/TimeReference      
              /rosout                      17 msgs    : rosgraph_msgs/Log              
              /rosout_agg                   1 msg     : rosgraph_msgs/Log              
              /tf                     5792134 msgs    : tf2_msgs/TFMessage
`
```

The new error

geo@geo-X570-GAMING-X:~/allan_ws$ rosrun allan_variance_ros allan_variance /home/geo/allan_ws/cooked.bag /home/geo/allan_ws/src/allan_variance_ros/config/xsens.yaml
[ INFO] [1693563181.691655459]: Bag Folder = /home/geo/allan_ws/cooked.bag
[ INFO] [1693563181.692535029]: Config File = /home/geo/allan_ws/src/allan_variance_ros/config/xsens.yaml
[ INFO] [1693563181.692582439]: Bag filenames count: 1
[ INFO] [1693563181.692805242]: Successfully read config file: /home/geo/allan_ws/src/allan_variance_ros/config/xsens.yaml
[ INFO] [1693563181.692833686]: imu_topic: /imu/data
[ INFO] [1693563181.692877239]: imu_rate: 400
[ INFO] [1693563181.692898018]: measure_rate: 400
[ INFO] [1693563181.692914810]: sequence_time: 14400
[ INFO] [1693563181.692940599]: Batch computor constructed
[ INFO] [1693563181.692955136]: Processing rosbag /home/geo/allan_ws/cooked.bag
[ INFO] [1693563181.692971107]: Processing /home/geo/allan_ws/cooked.bag ...
[ INFO] [1693563181.692988800]: Writing output to: /home/geo/allan_ws/cooked.bag/allan_variance.csv
`[ERROR] [1693563181.693018898]: Could not open the file for writing: /home/geo/allan_ws/cooked.bag/allan_variance.csv`
[ INFO] [1693563181.693045909]: Total computation time: 0.000599 s
[ INFO] [1693563181.693060216]: Data written to allan_variance.csv

why it tries to create csv inside the bag ? :confused:
